mip-html-tabs/README.md, mip-html-tabs/mip-html-tabs.js, mip-html-tabs/package.json
=> mip-html-tabs

mip-wkad-config/README.md, mip-wkad-config/mip-wkad-config.js, mip-wkad-config/package.json, mip-wkad/README.md, mip-wkad/mip-wkad.js, mip-wkad/package.json, mip-wkfun/README.md, mip-wkfun/mip-wkfun.js, mip-wkfun/package.json
=> 寻医问药3g mip页面的广告组件

mip-appdl/mip-appdl.js, mip-appdl/package.json, mip-filter/README.md, mip-filter/mip-filter.js, mip-filter/mip-filter.less, mip-filter/package.json, mip-nav-slidedown/README.md, mip-nav-slidedown/mip-nav-slidedown.js, mip-nav-slidedown/mip-nav-slidedown.less, mip-nav-slidedown/package.json
迁移mip-nav-slidedown 和mip-filter组件，增加filter的hash功能
=> 迁移mipengine官网所用组件

mip-360doc-script/README.md, mip-360doc-script/mip-360doc-script.js, mip-360doc-script/package.json
=> mip-360doc-script业务组件提交

mip-sidebar/README.md, mip-sidebar/mip-sidebar.js, mip-sidebar/mip-sidebar.less, mip-sidebar/package.json, mip-sidebar/setting/example.preset
=> add: 新增 mip-sidebar 侧边栏组件

mip-lightbox/README.md, mip-lightbox/mip-lightbox.js, mip-lightbox/mip-lightbox.less
=> mip-lightbox 组件升级

mip-360doc-script/README.md, mip-filter/README.md, mip-stats-ajk/README.md
=> update: 组件线上地址替换

changelog.md
=> update: 上线日志

mip-360doc-script/mip-360doc-script.js
=> mip-360doc-script组件业务逻辑修改

mip-stats-ajk/README.md, mip-stats-ajk/mip-stats-ajk.js
=> remove the zepto dependency

changelog.md
=> update: log

mip-sidebar/README.md, mip-sidebar/mip-sidebar.js, mip-sidebar/mip-sidebar.less
- README.md 更新
- 功能升级支持同一页面多个组件
=> update: mip-sidebar 组件

changelog.md, mip-changyan/README.md
=> update: 更新上线日志，更新新增组件线上地址

mip-ad/README.md, mip-ad/mip-ad-imageplus.js, mip-ad/mip-ad-imageplus.md, mip-ad/mip-ad.js
- 增加广告类型-图加广告
- 广告代码兼容错误type导致的控制的报错
=> update: 广告更新

mip-xueyou-article/README.md, mip-xueyou-article/mip-xueyou-article.js, mip-xueyou-article/package.json
=> 版本升级，增加统计功能

mip-youth-tb360/README.md, mip-youth-tb360/mip-youth-tb360.js, mip-youth-tb360/package.json, mip-youth-ttyd/README.md, mip-youth-ttyd/mip-youth-ttyd.js, mip-youth-ttyd/package.json
=> '今日头条广告推荐'

mip-360doc-script/mip-360doc-script.js
=> mip-360doc-script 自有业务逻辑修改

mip-360doc-script/mip-360doc-script.js
=> mip-360doc-script 组件自有业务逻辑修改

mip-wkad-config/README.md, mip-wkad-config/mip-wkad-config.js, mip-wkad/README.md, mip-wkad/mip-wkad.js, mip-wkfun-club/README.md, mip-wkfun-club/mip-wkfun-club.js, mip-wkfun-club/package.json, mip-wkfun/README.md, mip-wkfun/mip-wkfun.js
=> 增加mip-wkfun-club组件，更新其它组件功能

mip-wkad-config/mip-wkad-config.js, mip-wkfun-club/mip-wkfun-club.js, mip-wkfun/mip-wkfun.js
=> update files http to https

mip-nav-slidedown/README.md
=> 修改mip-nav-slidedown菜单说明文档

mip-youth-ttyd/mip-youth-ttyd.js, mip-youth-ttyd/package.json
=> '青网移动热点推荐广告位代码修改'

mip-dp-script/mip-dp-script.js, mip-dp-script/package.json
修改mip-dp-script.js，更换载入script方式
=> update mip-dp-script,fix bug

mip-ad-video/README.md, mip-ad-video/mip-ad-video.js, mip-ad-video/mip-ad-video.less, mip-ad-video/package.json
=> 新增带有广告的播放组件

mip-news-recommend/mip-news-recommend.js
=> 修复组件跳转相关问题

mip-news-recommend/mip-news-recommend.js
=> 新闻推荐组件更新：优化链接拼接逻辑

mip-yxdown-shielding-page/README.md, mip-yxdown-shielding-page/mip-yxdown-shielding-page.js, mip-yxdown-shielding-page/mip-yxdown-shielding-page.less, mip-yxdown-shielding-page/package.json
=> 修复格式错误导致不能运行的bug

mip-ad/mip-ad-ssp.md
因为 ssp 的测试 id 不稳定，且容易在使用时忘记修改，所以 demo 值改成 xxxtodo
=> 修改组件文档demo

mip-a5-loadmore/README.md, mip-a5-loadmore/mip-a5-loadmore.js, mip-a5-loadmore/package.json
a5创业网mip改装，加载更多列表所需业务逻辑组件
以修改符合相关规范并通过FECS检查
=> a5创业网加载更多列表逻辑组件（规范代码）

mip-ck-browser/README.md, mip-ck-browser/ck-browser.js, mip-ck-browser/mip-ck-browser.js, mip-ck-browser/package.json, mip-ck-location/README.md, mip-ck-location/ck-location.js, mip-ck-location/mip-ck-location.js, mip-ck-location/package.json
康网中医频道：又增加了一个mip-ck-location组件，根据不同的地区展示不同的内容
=> 康网中医频道:add mip-ck-browser 根据手机浏览器类型加载不同的内容/add mip-ck-location 根据不同地区展示不同的内容

mip-ck-browser/mip-ck-browser.js, mip-ck-location/README.md, mip-ck-location/mip-ck-location.js
=> 更新康网中医页面mip-ck-location和mip-ck-browser组件：add environment class

mip-news-iframe-interface/README.md, mip-news-iframe-interface/mip-news-iframe-interface.js, mip-news-iframe-interface/package.json
=> 提交新闻资讯iframe双向通信接口组件

mip-ck-browser/mip-ck-browser.js, mip-ck-location/mip-ck-location.js
修复mip-ck-location和mip-ck-browser，增加className的bug。
=> 康网中医详情页面：fixed browser location add class-name bug

mip-down-script/mip-down-script.js
=> 修改组件中图片未使用组件

mip-html-ajax/README.md, mip-html-ajax/mip-html-ajax.js, mip-html-ajax/package.json
=> mip-html-ajax更新

mip-360doc-script/mip-360doc-script.js
=> mip-360doc-script.js 自有业务逻辑修改

mip-ck-ad/mip-ck-ad.js
=> 康网问答详情页面：add show baidu union ad in UC browser

mip-ad/mip-ad-qwang.js, mip-ad/mip-ad-qwang.md
- 修改投放代码支持悬浮广告，引入//su.bdimg.com/static/dspui/js/umf_mip.js
- 过fecs规范
=> 修改悬浮投放脚本参数，过fecs

mip-bsml-fixedbar/mip-bsml-fixedbar.js
=> 更改弹出表单滑动整个页面滑动的bug

mip-wkfun-medicine/mip-wkfun-medicine.js
修改了mip-wkfun-medicine.js里的一些程序问题。
=> 修改了mip-wkfun-medicine.js

mip-bsml-multiselect/mip-bsml-multiselect.js
mip-bsml-multiselect修复下拉框被遮挡的bug
=> mip-bsml-multiselect修复下拉框被遮挡的bug

mip-cr173-tags/mip-cr173-tags.js
就把获取的值转成了大写。然后把对应的值改成了大写。。其他什么都没改。。
fecs也是通过的。。。pearl
=> 改了下。把获取的值变成了大写

mip-form/README.md, mip-form/mip-form.js, mip-form/mip-form.less
=> 增加http表单逻辑

mip-sample/mip-sample.js
Reverts mipengine/mip-extensions#330
=> Revert "更新naboo函数"

mip-cr173-conut/mip-cr173-conut.js
=> 就把http改成https了

mip-content-readmore/mip-content-readmore.js, mip-content-readmore/package.json
观察到的情况是，如果readmore发生在图片异步加载之前就正常，否则会图片重复显示。
把readmore获取到的html去掉<img .*?>就正常了。
=> readmore 特定情况下图片重复显示

mip-analytics/README.md, mip-analytics/mip-analytics.js, mip-analytics/mip-analytics.less, mip-analytics/package.json
=> mip-analytics 组件

mip-accordion/mip-accordion.js, mip-accordion/package.json
=> 升级accordion组件

mip-cr173-tags/mip-cr173-tags.js
=> 就换了个地方展示适配的内容

mip-sample/mip-sample.js
=> naboo涉及组件更新

mip-gototop/mip-gototop.js, mip-gototop/package.json
gototop添加显示延时
在html中使用delay属性配置，默认为0始终显示
=> gototop add display delay

mip-accordion/mip-accordion.js
=> change accordion

mip-baiyun-map/README.md, mip-baiyun-map/mip-baiyun-map.js, mip-baiyun-map/mip-baiyun-map.less, mip-baiyun-map/package.json
功能：  
- 公司位置标记  
- 查询去公司路线（公交 / 驾车）  
> 重新PR一次，谢谢。只剩百度地图本身的全局变量没有通过FECS，less 只是 WARN
=> mip-baiyun-map

mip-showmore/README.md, mip-showmore/mip-showmore.js, mip-showmore/mip-showmore.less, mip-showmore/package.json
=> 新增showmore组件

mip-360doc-script/mip-360doc-script.js
mip-360doc-script.js  自有业务逻辑修改
=> mip-360doc-script.js  自有业务逻辑修改

mip-experiment/README.md, mip-experiment/mip-experiment.js, mip-experiment/mip-experiment.less, mip-experiment/package.json
=> 新增mip-experiment前端实验组件

mip-accordion/mip-accordion.js, mip-accordion/package.json
=> update: 升级 mip-accordion 折叠组件

mip-ad/mip-ad-imageplus.js
Reverts mipengine/mip-extensions#480
=> 回滚- Revert "update: 图加广告修复上线"

mip-ad/mip-ad-imageplus.js
Reverts mipengine/mip-extensions#488
=> 重新上线  "回滚- Revert "update: 图加广告修复上线""

mip-infinitescroll/README.md, mip-list/README.md, mip-semi-fixed/README.md, mip-semi-fixed/mip-semi-fixed.js, mip-semi-fixed/mip-semi-fixed.less, mip-semi-fixed/package.json
Reverts mipengine/mip-extensions#487
=> 重新上线 "回滚 Revert "update: 新增 mip-semi-fixed 滑动悬浮组件""

mip-appdl/mip-appdl.js, mip-appdl/package.json
=> change appdl

mip-ck-browser/ck-browser.js, mip-ck-browser/package.json
mip-ck-browser修改组件，兼容移动端ios系统和安卓系统上的uc浏览器，qq浏览器，Safair浏览器。
=> mip-ck-browser

mip-cr173-ppzs/mip-cr173-ppzs.js
先把弹出的推荐内容去掉了。。这个暂时先用着。。
我还在用你们提供的新组件做一个新的类似功能。。然后更新这个组件
=> 去掉了些东西，先上线用着

mip-ad/README.md, mip-ad/mip-ad-ssp.md
=> 修改mip-ad ssp内容联盟组件示例

mip-form/mip-form.js
现在修复后的效果：http://cp01-lizhaoming-dev.epc.baidu.com:8291/mip?ext=%7B%22url%22:%22https://gkrace.github.io/test_component/mip-form/mip-form_repair.html%22%2C%22lid%22:2%7D
之前的效果：
https://www.mipengine.org/validator/preview/s?url=https://gkrace.github.io/test_component/mip-form/mip-form_online.html
=> 为了解决 ios 的 UC 浏览器在SF悬浮头部 fixed 位置混乱问题   

mip-wkad/mip-wkad.js, mip-wkad/package.json
=> 增加几个广告条件显示判断

mip-showmore/README.md, mip-showmore/mip-showmore.js, mip-showmore/mip-showmore.less, mip-showmore/package.json, mip-showmore/setting/example.preset
=> mip-showmore组件增加对嵌套的支持

mip-sidebar/mip-sidebar.js
=> sidebar组件修复

mip-form/mip-form.js, mip-form/package.json
=> modify mip-form target

mip-accordion/README.md, mip-accordion/setting/example.preset
修改reamme 示例 进行说明嵌套规则 
示例页面：https://gkrace.github.io/test_component/mip_accordion/mip-accordion_update.html
=> 增加accordion 组件嵌套规则

mip-news-recommend/mip-news-recommend.js, mip-news-recommend/package.json
=> recovery old logic

mip-news-recommend/mip-news-recommend.js, mip-news-recommend/package.json
revert to previous version for solving dependency problems
=> revert to previous version

mip-news-recommend/mip-news-recommend.js, mip-news-recommend/package.json
=> add parse cache url api

mip-sidebar/README.md, mip-sidebar/mip-sidebar.js, mip-sidebar/package.json
=> 修复sidebar弹出后，背景主体可以滚动的bug

mip-install-serviceworker/README.md, mip-install-serviceworker/mip-install-serviceworker.js, mip-install-serviceworker/urlRewriter.js, mip-install-serviceworker/util.js
增加浏览器不支持 service worker 的 fallback 方案
=> add no service worker fallback

mip-filter/README.md, mip-filter/mip-filter.js
=> mip-filter增加自定义筛选文字

mip-stats-baidu/mip-stats-baidu.js
=> force mip-stats-baidu to use https

mip-360doc-script/mip-360doc-script.js
=> mip-360doc-script.js 资源图片修改

mip-stats-baidu/mip-stats-baidu.js, mip-stats-baidu/package.json
Reverts mipengine/mip-extensions#827
=> Revert "Mip mip-stats-baidu bugfix"

mip-form/README.md, mip-form/mip-form-fn.js, mip-form/mip-form.js, mip-form/mip-form.less, mip-form/package.json
=> add fetch to mip-form.

package-lock.json, package.json
-  将package.json中依赖改为devDependencies；
- 添加 package-lock.json。
=> chore:更改package.json中依赖关系

.github/PULL_REQUEST_TEMPLATE.md
=> feat:加入pull request模版

mip-filter/mip-filter.js, mip-filter/package.json
=> fix:修复mip-filter筛选问题

mip-stats-baidu/mip-stats-baidu.js
=> fix:fix empty data-stats-baidu-obj bug for mip-stats-baidu

mip-stats-baidu/mip-stats-baidu.js, mip-stats-baidu/package.json
=> fix:hm.js loading bug for mip-stats-baidu

mip-form/mip-form-fn.js, mip-form/mip-form.js, mip-form/package.json
=> feat:去掉mip-form中的password和file限制

mip-39ad/mip-39ad.js, mip-39ad/package.json
=> 将define之外的变量重新添加到define里面

mip-filter/mip-filter.js, mip-filter/package.json
修复mip-filter点击返回按钮hash与页面状态不同步问题
=> fix:修复mip-filter点击返回按钮hash与页面状态不同步问题

docs/README.md
=> docs:组件目录修改后更新文档

README.md
=> docs: 更新readme脚本引用

src/mip-bind/README.md
=> docs: 修改mip bind文档

src/mip-audio/README.md
fix <https://github.com/mipengine/www.mipengine.org/issues/14>
=> fix: 修复 mip-audio 组件的预览功能

src/mip-lightbox/README.md, src/mip-lightbox/mip-lightbox.js, src/mip-lightbox/mip-lightbox.less, src/mip-lightbox/package.json, src/mip-lightbox/setting/example.preset
=> feat: 增加mip-lightbox对滚动的支持

src/mip-sidebar/mip-sidebar.js, src/mip-sidebar/mip-sidebar.less, src/mip-sidebar/package.json
sidebar 打开和关闭时，加入 mask 层动画效果，避免闪动的用户体验问题
=> fix: 升级sidebar 组件，加入 mask 动画效果

src/mip-showmore/mip-showmore.js
=> fix: 修改高度问题

src/mip-app-banner/README.md, src/mip-stats-baidu/README.md
=> docs: 优化组件文档

src/mip-showmore/README.md
=> docs: 增加mip showmore按钮展开样式文档

src/mip-showmore/mip-showmore.js, src/mip-showmore/package.json
=> feat: 支持close样式就不走老逻辑

src/mip-showmore/mip-showmore.js
=> feat: event问题解决

src/mip-showmore/README.md
=> feat: 更新mip showmore使用文档

src/mip-nav-slidedown/README.md, src/mip-nav-slidedown/mip-nav-slidedown.js, src/mip-nav-slidedown/mip-nav-slidedown.less, src/mip-nav-slidedown/package.json, src/mip-nav-slidedown/setting/example.preset, src/mip-stats-tianrun/README.md, src/mip-stats-tianrun/mip-stats-tianrun.js, src/mip-stats-tianrun/package.json, src/mip-vd-tabs/README.md, src/mip-vd-tabs/mip-vd-tabs.js, src/mip-vd-tabs/mip-vd-tabs.less, src/mip-vd-tabs/package.json, src/mip-vd-tabs/tab.js
=> docs: 添加组件

src/mip-map/README.md
=> docs: 地图组件文档更新

src/mip-custom/dom.js, src/mip-custom/mip-custom.js, src/mip-custom/package.json, src/mip-custom/url.js
=>  fix:customDeferredGetConf

src/mip-install-serviceworker/README.md
=> docs: mip install service worker

src/mip-access/README.md
=> docs: mip access

src/mip-custom/package.json, src/mip-custom/url.js
=> feat: add params for content union

src/mip-audio/README.md, src/mip-audio/mip-audio.js, src/mip-audio/mip-audio.less, src/mip-audio/package.json
=>  feat: 升级audio功能，支持交互DOM可配置，进度条可拖动，兼容PC端2

src/mip-ad/README.md
=> docs: 修改广告文档

src/mip-bind/README.md
=> docs: 增加 bind demo

src/mip-vd-baidu/README.md
测试通过：
1. 源： <https://static.xuexb.com/miptest/ok2.html?dd>
2. MIP Cache： <http://static-xuexb-com.mipcdn.com/c/s/static.xuexb.com/miptest/ok2.html?ddd>
=> fix: 修复图片链接

src/mip-gototop/mip-gototop.js, src/mip-gototop/mip-gototop.less, src/mip-gototop/package.json
mip-gototop 组件隐藏实现是通过 opacity，导致元素下的元素不能点击
=> fix: 修改 GitHub #976 问题

src/mip-audio/setting/example.preset
=> feat: 增加mip-audio组件preset设置文件

src/mip-bind/README.md
=> docs: 修改大小写

src/mip-bind/README.md, src/mip-bind/mip-compile.js
=> fix: 修复 mip-bind 组件 class 覆盖问题

src/mip-iask-business/mip-iask-business.js, src/mip-iask-business/package.json
=> 更新广告代码Patch 31

src/mip-iask-business/mip-iask-business.js
=> 更新点击事件名称 Update mip-iask-business.js

src/mip-bind/mip-compile.js, src/mip-bind/package.json
=> 解决class覆盖的问题

src/mip-infinitescroll/README.md, src/mip-infinitescroll/mip-infinitescroll.js, src/mip-infinitescroll/package.json
=> feat: mip-infinitescroll 文档代码优化

src/mip-access/README.md
=> docs: 修改access文档

src/mip-access/README.md
=> docs: 修改文档中表格样式

src/mip-ad/mip-baidu-wm-ext.js, src/mip-ad/package.json
=> feat:增加网盟广告实验

src/mip-wkad-config/mip-wkad-config.js, src/mip-wkad-config/package.json
Reverts mipengine/mip-extensions#1011
=> Revert "增加搜索词功能"

src/mip-custom/package.json, src/mip-custom/url.js
=> feat:custom-addEqid

src/mip-iask-business/mip-iask-business.js
=> Update mip-iask-business.js 麻烦审核一下，谢谢！

src/mip-iask-business/mip-iask-business.js, src/mip-iask-business/package.json
=> 新增医疗广告以及修改规范

src/mip-ad/mip-ad-baidu.js, src/mip-ad/mip-baidu-wm-ext.js, src/mip-ad/package.json
=> feat:转全反屏蔽的广告优化，上线普通广告的小流量实验

src/mip-map/README.md
=> docs: 更新文档链接

src/mip-story/README.md, src/mip-story/mip-progress.js, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-hint.js, src/mip-story/mip-story-layer.js, src/mip-story/mip-story-share.js, src/mip-story/mip-story-view.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less, src/mip-story/package.json
=> feat: 增加 mip-story 组件

src/mip-story/mip-story-hint.js, src/mip-story/mip-story.less, src/mip-story/package.json
=> feat: 修改图片地址

src/mip-story/mip-progress.js, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-hint.js, src/mip-story/mip-story-layer.js, src/mip-story/mip-story-share.js, src/mip-story/mip-story.js, src/mip-story/package.json
=> feat: 没有历史记录时不现实关闭按钮

src/mip-iask-business/mip-iask-business.js
=> 更新统计代码的加载顺序

src/mip-story/README.md
=> docs: 更新组件文档

src/mip-ad/mip-ad-baidu.js, src/mip-ad/package.json
=> feat: 增加mip广告日志

src/mip-bind/README.md, src/mip-bind/mip-compile.js, src/mip-bind/package.json
=> feat: 增加删除属性功能

src/mip-lightbox/mip-lightbox.js, src/mip-lightbox/package.json, src/mip-sidebar/mip-sidebar.js, src/mip-sidebar/package.json
虽然目前不会遇到问题，但还是改下吧。因为一添加 JS 严格模式在 iOS9.3 以下就挂了，<https://caniuse.com/#search=const>
=> fix: 修复组件内使用 const 语法

src/mip-iask-business/mip-iask-business.js
=> encodeURIComponent 方法修复，之前传进去的是字符串，改为传对象

src/mip-infinitescroll/README.md, src/mip-infinitescroll/mip-infinitescroll.js, src/mip-infinitescroll/package.json
=> fix: 修复无限滚动超时参数

src/mip-bind/mip-bind.js, src/mip-bind/mip-compile.js, src/mip-bind/mip-data.js, src/mip-bind/package.json
=> fix: form element bind

src/mip-ad/mip-ad-baidu.js, src/mip-ad/package.json
=> delete sample part.

src/mip-bind/README.md
=> docs: fix readme error

src/mip-search-video/mip-search-video.js
=> fix: 删除merge产生的diff

src/mip-story/README.md
=> docs: update mip sotry readme

src/mip-custom/data.js, src/mip-custom/dom.js, src/mip-custom/mip-custom.js
拆分上线 https://github.com/mipengine/mip-extensions/pull/1046 代码。
=> feat: 增加{{}}请求追查日志

src/mip-custom/data.js, src/mip-custom/dom.js, src/mip-custom/mip-custom.js
This reverts commit 4635b904ce50c6498dfa1afc12fd54f625b26086.
=> Revert "feat: 增加{{}}请求追查日志 (#1097)"

src/mip-sidebar/mip-sidebar.js, src/mip-sidebar/mip-sidebar.less, src/mip-sidebar/package.json
修复sidebar reopen后无法响应的问题，详见 #1045
=> fix sidebar bug when reopen

src/mip-share/mip-share.less, src/mip-share/package.json, src/mip-share/share/share.js, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-share.js, src/mip-story/mip-story.js, src/mip-story/package.json
=> 修复QQ/UC/手百等浏览器内分享吊起失败的问题，新增小故事微信内二次分享的配置逻辑

package.json, sample/index.html, sample/oscar.html, tools/site.js
=> add sample

src/mip-story/mip-story.js, src/mip-story/package.json
=> fix:mip-story a tag redirect bug

src/mip-custom/mip-custom.js
=>  feat: 增加服务端数据日志

src/mip-custom/package.json, src/mip-custom/url.js
=> feat: 搜索合作页增加内容联盟导流字段fn

src/mip-infinitescroll/infinitescroll.js, src/mip-infinitescroll/package.json
=> fix: infinityscroll in ios iframe bug

src/mip-story/README.md
=> doc:story desc

src/mip-story/README.md
=> doc:story doc format

src/mip-story/README.md, src/mip-story/mip-story-hint.js, src/mip-story/mip-story.js, src/mip-story/package.json
=> feat:story swipe tips show and some doc format

src/mip-filter/mip-filter.js, src/mip-filter/package.json
=> fix:修复点击“filter-num”数字，会出现“没有符合的内容”

sample/mip-filter/mip-filter.html, src/mip-filter/mip-filter.js
=> fix: 修复沙盒下不能正常显示bug

sample/mip-showmore.html, src/mip-showmore/README.md, src/mip-showmore/mip-showmore.js, src/mip-showmore/package.json
fix: bug of nested layers, add feat of bufferheight
- 说明：弹性缓冲高度，判读 maxheight 时会加上此高度进行判断
- 取值：数字
- 必选项：否
=> fix: bug of nested layers, add feat of bufferheight

src/mip-story/README.md, src/mip-story/animate-preset.js, src/mip-story/package.json
=> feat:add story inner aniamte-in type

src/mip-story/mip-story-share.js, src/mip-story/mip-story.js, src/mip-story/package.json
=> feat:story share for searchCraft

sample/mip-showmore.html, src/mip-showmore/README.md, src/mip-showmore/mip-showmore.js
=> fix: showmore 添加click事件 解决点透问题

src/mip-story/README.md, src/mip-story/animation-util.js, src/mip-story/animation.js, src/mip-story/mip-progress.js, src/mip-story/mip-story-view.js, src/mip-story/package.json
=> feat: add auto-advanced-after animation

src/mip-showmore/mip-showmore.js
=> fix: showmore 兼容问题

src/mip-story/mip-story-share.js
=> fix：mip-story 在简搜下分享的问题

src/mip-custom/data.js, src/mip-custom/package.json
=> feat: 搜索合作页增加广告模板js配置

src/mip-story/README.md, src/mip-story/mip-progress.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less
=> feat: 修改头部样式&添加熊掌号站点信息

sample/mip-story/layout-templates.html, src/mip-story/mip-story.less, src/mip-story/package.json
=> feat：修改小故事模板字体大小

.fecsrc, src/mip-widget-full-height/README.md, src/mip-widget-full-height/mip-widget-full-height.js, src/mip-widget-full-height/package.json
=> mip-widget-full-height 组件

src/mip-custom/mip-custom.js
=> feat: 修改es6的语法mip1中不兼容

src/mip-custom/mip-custom.js
=> fix: 请求URL替换，解决不能带上特殊参数问题

src/mip-custom/mip-custom.js
=> feat: mip-custom如果加载慢于小说shell需要先向小说shell发事件通知

src/mip-custom/mip-custom.js
=> feat: 定制化组件升级2

src/mip-story/mip-progress.js, src/mip-story/package.json
=> fixed: 结果页打开 熊掌号露出bug

src/mip-story/mip-progress.js, src/mip-story/mip-story-service.js
=> feat:添加熊掌号跳转

src/mip-story/mip-progress.js, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-config.js, src/mip-story/mip-story-slider.js, src/mip-story/mip-story-view.js, src/mip-story/mip-story.js, src/mip-story/package.json
#1233 
增加 分享页关闭按钮点击统计、更多推荐点击统计、来源外链点击统计、翻页统计
线上小故事 统计项增加
=> feat:小故事增加埋点 【免测】

src/mip-ad-ecom/mip-ad-ecom.less
#1253 
去掉less中min-height: 343px;
线上使用mip-ad-ecom的组件未配置height的。
chrom
safair
=> feat: mip-ad-ecom组件去掉固定高度

sample/mip-story/mouse.html, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-slider.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less
#1248 
增加鼠标翻页
线上小故事 需测兼容
- 鼠标正常翻页
- 手机正常翻页
=> feat: mip-story 增加鼠标翻页支持

sample/mip-story/preload.html, src/mip-story/README.md, src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-config.js, src/mip-story/mip-story-img.js, src/mip-story/mip-story-slider.js, src/mip-story/mip-story-video.js, src/mip-story/mip-story-view.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less
#1257
- 图片、音/视频 懒加载
- 新增mip-story-img 组件
线上小故事会影响音频加载、视频加载，图片为新增组件 暂无使用
- 资源正常加载
=> feat: 优化小故事静态资源懒加载

src/mip-story/mip-story-bookend.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less
#1261 
1、样式微调
2、推荐链接打点，细化到每个链接打点
线上小故事样式
- 样式正常
- 打点正常
=> feat: 尾页优化

src/mip-story/mip-story-bookend.js, src/mip-story/mip-story-service.js, src/mip-story/mip-story.less
#1267
小故事推荐链接新增http跳转支持
新增http跳转
推荐链接无论是http还是https，都正常跳转
=> feat: 增加http跳转支持

src/mip-custom/mip-custom.js
=>  feat: 为common请求日志打点设置字段

src/mip-story/mip-story-img.js, src/mip-story/mip-story-video.js
#1269
修复可能出现的问题
使用了`mip-story-img`且添加了自定义css动画时
- 一个`mip-story-img`只创建一次图片
=> 修复<mip-story-img>带有自定义动画时，会重复创建图片的问题

src/mip-custom/mip-custom.js
=> fix: 修复common异常打点判断时机

src/mip-story/mip-progress.js, src/mip-story/mip-story-config.js, src/mip-story/mip-story-service.js, src/mip-story/mip-story-slider.js, src/mip-story/mip-story-state.js, src/mip-story/mip-story-storage.js, src/mip-story/mip-story.js, src/mip-story/package.json
#1280 
记住用户浏览状态
所有小故事
**5、自测机型和浏览器**
=> 小故事增加浏览状态保持功能

src/mip-custom/mip-custom.js
=>  feat: 新增广告展现埋点判断字段

src/mip-custom/novelFeature.js
#1290 
bugfix
依赖模块未引入
线上广告合并
chrome
=> fix: 小说广告合并bugfix

src/mip-story/animate-preset.js, src/mip-story/animation.js, src/mip-story/mip-story-service.js, src/mip-story/mip-story-slider.js, src/mip-story/mip-story-video.js, src/mip-story/mip-story-view.js, src/mip-story/mip-story.js, src/mip-story/mip-story.less, src/mip-story/package.json
#1292 
**feature:** 
1、视频支持单循环
2、视频支持mip布局
3、少于两页时，可正常浏览
**fix:**
1、动画播放异常
2、ios下，初始页是视频时，无法自动播放
线上
- 视频、动画正常播放
=> fix: mip-story 动画问题

src/mip-custom/mip-custom.js
=> fix:小说广告展示打点修改判断字段

src/mip-stats-baidu/mip-stats-baidu.js
#1312 
1、修改了关于点击统计的部分
- 百度统计的所有日志发送
**3、需要覆盖的场景和case**
**4、自测机型和浏览器**
=> 【免测】fixed: 保证不了组件渲染顺序的前提下保证点击统计机制正常运行

src/mip-audio/mip-audio.js
**1、升级点** 同 https://github.com/mipengine/mip2-extensions/pull/399
=> fix: Controls audio when page is switching

src/mip-custom/package.json, src/mip-custom/url.js
[#1324](https://github.com/mipengine/mip-extensions/issues/1324)
医疗mip迁移pc，mipserver请求携带pc标识参数
=> mipserver请求携带pc标识参数

src/mip-custom/url.js
=> 为了排查无效pv，增加一个参数

src/mip-custom/novelFeature.js
https://github.com/mipengine/mip2-extensions/pull/535
这次的更新必须在 mip-shell-xiaoshuo 上线之后才能上线
配合小说组件一起测试
=> 完成小说 nocache 机制

src/mip-custom/url.js
=> 追查无效PV，增加参数

src/mip-custom/url.js
=> 无效PV又增加一个参数

src/mip-custom/mip-custom.js
files #1333
定制化医疗业务， 除一些特殊资源外， 其他资源方私自增加的链接 ， 通过代码屏蔽
影响定制化医疗业务A区页面， 把A区隐藏的a链接屏蔽跳转
1） 医疗合作页A区非特殊网站跳转
2） 医疗合作页A区A区特殊网站 的跳转
3） 医疗合作页A区 B区和广告的跳转
**4、需要覆盖的场景和c经ase**
=> 定制化医疗业务增加屏蔽A区链接跳转功能

src/mip-custom/mip-custom.js
Reverts mipengine/mip-extensions#1334
=> Revert "定制化医疗业务增加屏蔽A区链接跳转功能"

src/mip-custom/url.js
#1346
结果页fenlei searchFrom order 字段透传至合作页并添加至common请求
合作页common请求
1、从结果页跳转至合作页，common请求中字段是否正常添加，能否正常跳转
- [ 是 ] 是否覆盖了sf打开mip页
- [ 是 ] 是否验证了极速服务mip页面效果
- [ 是 ] 是否覆盖了ios系统手机
- [ 是 ] 是否覆盖了安卓系统手机
- [ 是 ] 是否覆盖了iphone版式浏览器（比如qq、uc、chrome、safari、安卓自带浏览器）
- [ 是 ] 是否覆盖了手百
=> 结果页fenlei searchFrom order 字段透传

src/mip-custom/url.js
和 mip2 的 mip-custom 保持一致，在 standalone 的情况下添加 noshell 参数。
使用 mip-custom 的页面
代理测试，页面正常展现广告
=> 【免测】同步 mip-custom noshell 逻辑

src/mip-custom/url.js
mipengine/mip2-extensions#695
逻辑升级，独立站非mipcdn链接才出noshell
主要影响医疗部分页面
搜索结果页点出来的医疗第三方站点带noshell
mipcdn链接不带noshell
=> 修改出 noshell 的逻辑
